### ISSUE TITLE
Version 1.8.26: error: 'GNUTLS_CB_TLS_EXPORTER' undeclared

### ISSUE THREAD

**Issue by BKPepe** [marlam/msmtp#151]
Hi,

I tried to compile the msmtp 1.8.26 with SSL support, but I do have gnutls 3.7.1 and I can not compile it as it fails with this one:
```
mtls-gnutls.c: In function 'mtls_start':
mtls-gnutls.c:611:45: error: 'GNUTLS_CB_TLS_EXPORTER' undeclared (first use in this function); did you mean 'GNUTLS_CB_TLS_UNIQUE'?
  611 |                 mtls->is_tls_1_3_or_newer ? GNUTLS_CB_TLS_EXPORTER
      |                                             ^~~~~~~~~~~~~~~~~~~~~~
      |                                             GNUTLS_CB_TLS_UNIQUE
mtls-gnutls.c:611:45: note: each undeclared identifier is reported only once for each function it appears in
make[5]: *** [Makefile:478: mtls-gnutls.o] Error 1
make[5]: *** Waiting for unfinished jobs....
mv -f .deps/tools.Tpo .deps/tools.Po
mv -f .deps/net.Tpo .deps/net.Po
smtp.c: In function 'smtp_auth_oauthbearer':
smtp.c:973:49: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  973 |             if ((e = smtp_send_cmd(srv, errstr, "")) != SMTP_EOK)
      |                                                 ^~
smtp.c: In function 'smtp_auth_xoauth2':
smtp.c:1056:49: warning: zero-length gnu_printf format string [-Wformat-zero-length]
 1056 |             if ((e = smtp_send_cmd(srv, errstr, "")) != SMTP_EOK)
      |                                                 ^~
mv -f .deps/smtp.Tpo .deps/smtp.Po
mv -f .deps/conf.Tpo .deps/conf.Po
mv -f .deps/msmtp.Tpo .deps/msmtp.Po
```

It looks like it is caused by commit https://git.marlam.de/gitweb/?p=msmtp.git;a=commit;h=e9ae256f457739b5995ad4784d92fadc05cdcef4

**Comment by marlam** [comment]
`GNUTLS_CB_TLS_EXPORTER` first appeared in GnuTLS 3.7.2, released 3 years ago. I bumped the minimum GnuTLS requirement to reflect this.

Supporting 3.7.1 does not make sense since that version has [security problems](https://gnutls.org/security-new.html) that were fixed in later versions.

**Comment by BKPepe** [comment]
Thank you, @marlam, for looking into it! Much appreciated. 🙌 

Yeah, GnuTLS 3.7.1 is quite old indeed, but it is still being used in OpenWrt 22.03, which should be EoL soon. I might look at it to update it there, because Turris routers are using that version and most likely they will be until Christmas, they can not switch to it faster as they do not have manpower.

**Comment by marlam** [comment]
As a workaround, you can remove/disable the whole code block that starts with the comment "Get channel binding" (in lines 605-619 in `mtls-gnutls.c`).

That will effectively disable the SCRAM-*-PLUS authentication methods, but if you don't build with GNU SASL (libgsasl), you don't get support for these methods anyway.
